// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartyInvitationApp.Data;

#nullable disable

namespace PartyInvitationApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250306194755_SeedDataFixed")]
    partial class SeedDataFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartyInvitationApp.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            GuestEmail = "jpandit5253@conestogac.on.ca",
                            GuestName = "Virat Kohli",
                            PartyId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 21,
                            GuestEmail = "jpandit5253@conestogac.on.ca",
                            GuestName = "MS Dhoni",
                            PartyId = 11,
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            GuestEmail = "jpandit5253@conestogac.on.ca",
                            GuestName = "Rohit Sharma",
                            PartyId = 11,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfParty")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            DateOfParty = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cricket Champions Trophy",
                            Location = "Dubai International Stadium"
                        });
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Invitation", b =>
                {
                    b.HasOne("PartyInvitationApp.Models.Party", "Party")
                        .WithMany("Invitations")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("PartyInvitationApp.Models.Party", b =>
                {
                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
